#!/bin/bash

HDMI1=$(xrandr | grep 'HDMI1 connected');
LVDS1=$(xrandr | grep 'LVDS1 connected');
FEH_IMG=$(cat /home/$USER/.fehbg | sed -n '2p' | awk '{print $3}' | tr -d '\'\')

function feh_restore () {
  feh --bg-fill ${FEH_IMG}
}

function laptop () {
  xrandr --output LVDS1 --mode 1366x768
  xrandr --output HDMI1 --off
  pactl set-card-profile alsa_card.pci-0000_00_1b.0 output:analog-stereo
  feh_restore
}

function both () {
  xrandr --output LVDS1 --auto --primary --output HDMI1 --mode 1920x1080\
  --below LVDS1
  pactl set-card-profile alsa_card.pci-0000_00_1b.0 output:hdmi-stereo
  feh_restore
}

function hdmi () {
  xrandr --output HDMI1 --primary --mode 1920x1080
  xrandr --output LVDS1 --off
  pactl set-card-profile alsa_card.pci-0000_00_1b.0 output:hdmi-stereo
  feh_restore
}

# using '$ tv laptop'

if [[ $1 = laptop ]]; then
  if [[ -n $LVDS1 ]]; then
    laptop
    feh_restore
    notify-send 'Audio and Video through Laptop only.'
  else
    notify-send 'LVDS1 is not connected'
  fi
fi

# using '$ tv both'

if [[ $1 = both ]]; then
  if [[ -n $LVDS1 ]]; then
    if [[ -n $HDMI1 ]]; then
      both
      notify-send 'Audio through HDMI, Video through both.'
    else
      notify-send 'HDMI not connected.'
    fi
  fi
fi

# using '$tv hdmi'

if [[ $1 = hdmi ]]; then
  if [[ -n $HDMI1 ]]; then
    hdmi
    feh_restore
    notify-send 'Audio and Video through HDMI only.'
  else
    notify-send 'HDMI not connected.'
  fi
fi

# help prompt

if [[ -z "$1" ]]; then
  echo -e 'Type --help for usage.'
fi
